#!/bin/bash

echo "🔄 تحديث Packagist..."
echo ""
echo "الخطوات المطلوبة:"
echo ""
echo "1️⃣ افتح المتصفح واذهب إلى:"
echo "   https://packagist.org/packages/eng-mohamedemad-dev/command-module-generator"
echo ""
echo "2️⃣ اضغط على زر 'Update' الأخضر"
echo ""
echo "3️⃣ انتظر 30-60 ثانية حتى يكتمل التحديث"
echo ""
echo "4️⃣ تأكد من ظهور v1.0.0 في قائمة الإصدارات"
echo ""
echo "5️⃣ بعد التحديث، جرب:"
echo "   composer require eng-mohamedemad-dev/command-module-generator"
echo ""
echo "───────────────────────────────────────────────────────"
echo ""
echo "✅ تم رفع Tag v1.0.0 على GitHub بنجاح!"
echo "⏳ الآن ننتظر تحديث Packagist..."
echo ""
echo "📊 للتحقق من حالة الباكدج:"
echo "   curl -s https://repo.packagist.org/p2/eng-mohamedemad-dev/command-module-generator.json | python3 -m json.tool"
echo ""
